# Generated by Django 2.2.4 on 2019-08-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
